#!/usr/bin/env sh

set -eu

groupadd -f -g ${VOLUME_GID} --system www-data
useradd -d /var/www/ \
        -g ${VOLUME_GID} \
        --no-create-home \
        --no-user-group \
        --system \
        --shell $(which bash) \
        www-data || :

usermod -u ${VOLUME_UID} www-data
groupmod -g ${VOLUME_GID} www-data
# minimal directories ------------------------------------------------
mkdir -p /var/serve
chown -Rf ${VOLUME_UID}:${VOLUME_GID} /var/serve
# create logs --------------------------------------------------------
sudo -u www-data touch /var/serve/stdout.log
sudo -u www-data touch /var/serve/stderr.log
sudo mkdir -p /var/log/httpd
ln -sfvr /var/serve/stdout.log /var/log/httpd/
ln -sfvr /var/serve/stderr.log /var/log/httpd/
sudo chown -Rf www-data:www-data /var/log/httpd/
# bundle install -----------------------------------------------------
(cd /var/www/localhost/ && {
     ((test -f gems.rb && test -f gems.locked) && {
          export BUNDLE_JOBS=$(nproc)
          export BUNDLE_IGNORE_MESSAGES=true

          bundle install --clean
      })
 }) || :
