# vim:ft=yaml:
version: "3"

services:
  spin_web:
    build: { context: images/web }
    extra_hosts:
      - "web.spin.${DC_DOMAIN:-test}:127.0.0.1"
    expose: ["80"]
    environment:
      VOLUME_UID: ${UID:-1000}
      VOLUME_GID: ${GID:-1000}
      VIRTUAL_HOST: "web.spin.${DC_DOMAIN:-test}"
    volumes:
      - ..:/var/www/localhost/
      - web-gems:/usr/lib/ruby/gems/2.5.0/
      - web-bundle:/usr/lib/bundle/
    networks: [default, proxy]

volumes:
  web-gems:
  web-bundle:

networks:
  proxy:
    external: true

# Local Variables:
# mode: yaml
# End:
