#!/usr/bin/env sh

set -eu

mkdir -p "$POSTGRES_DATAPATH"
mkdir -p /run/postgresql/
mkdir -p /var/log/postgresql/
chown -fR postgres:postgres /run/postgresql/ /var/log/postgresql/

test -z "$(ls -A "$POSTGRES_DATAPATH")" || exit 0

chown -fR postgres:postgres "$POSTGRES_DATAPATH"
sudo -u postgres initdb -D "$POSTGRES_DATAPATH"
# config file (postgresql.conf) --------------------------------------
echo "include = '/etc/postgresql/postgresql.conf'" >> \
     "${POSTGRES_DATAPATH}/postgresql.conf"
